### ISSUE TITLE
Documentation improvement - requires inifile module

### ISSUE THREAD

**Issue by gregharvey** [s12v/puppet-blackfire#19]
Hi,

I'm getting this error:

```
Jan  3 10:39:59 foo puppet-agent[XXXXX]: Could not retrieve catalog from remote server: Error 400 on SERVER: Puppet::Parser::AST::Resource failed with error ArgumentError: Invalid resource type ini_setting at /etc/puppet/environments/dev/modules/blackfire/manifests/agent/config.pp:13 on node foo.codeenigma.net
```

And a quick look around implies it's because I need this module:
https://forge.puppet.com/puppetlabs/inifile/1.2.0

(See https://github.com/jippi/puppet-php/issues/117)

Would be good if the README stated that dependency, assuming it *is* a dependency. :-)

Thanks,

Greg

**Comment by s12v** [comment]
@gregharvey, dependencies are visible in Forge: https://forge.puppet.com/s12v/blackfire/dependencies

Could add it to README, but then they can become inconsistent :)

**Comment by gregharvey** [comment]
Fair enough! I'm not so familiar with the Puppet Forge site. I guess we should close this. :-)
