### ISSUE TITLE
Including blackfire module fails

### ISSUE THREAD

**Issue by kariboe** [s12v/puppet-blackfire#2]
Installed Puppet module to master. Included the class in one of my nodes

```
class { 'blackfire':
  server_id     => 'xxxxxx',
  server_token  => 'xxxxxx',
  agent         => { log_level => 1},
  php           => { log_level => 1 }
  notify        => Service['httpd'],
}
```

Result during Puppet run:
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: merge: unexpected argument type String, only expects hash arguments at opt/puppet_modules/production/forge_modules/current/blackfire/manifests/php.pp:14 on node xxxxxxxx

Any help is appreciated.

**Comment by s12v** [comment]
looks like your configuration misses a comma after `php           => { log_level => 1 }`, not sure if it's the source of the error though
