### ISSUE TITLE
Installation fails on Ubuntu Trusty

### ISSUE THREAD

**Issue by mbrodala** [s12v/puppet-blackfire#3]
The installation of this module fails on Ubuntu Trusty:

> Evaluation Error: Error while evaluating a Resource Statement, Could not find declared class apt at /.../blackfire/manifests/repo.pp:8:11 on node ...

Installing `puppetlabs-apt` fixes this issue. Is there some way to express this conditional dependency in your `metadata.json` so that the installation works right away? (Using librarian-puppet here.)

**Comment by s12v** [comment]
@mbrodala, I removed this dependency some time ago, because it's optional: b4baa5ab6d8182713102dbd0a10bc8c3758dd07a

**Comment by mbrodala** [comment]
Hm, that's odd then. As you can see I get an error without `puppetlabs-apt`...

**Comment by s12v** [comment]
@mbrodala, yes, because apt is optional. You can skip repo management, then it's not required. But if you use default settings, and don't have it you will have an error.

I see it causes confusion :( maybe I'll just put it back in manifest.

**Comment by mbrodala** [comment]
Or make `false` the default value of `manage_repo` with a suitable hint that `puppetlabs-apt` is required for Debian/Ubuntu/etc.

**Comment by s12v** [comment]
fixed in 1.4.0

**Comment by mbrodala** [comment]
Thanks a lot. :-)
