### ISSUE TITLE
Configuration files on Ubuntu with PHP 7

### ISSUE THREAD

**Issue by mvhirsch** [s12v/puppet-blackfire#6]
This won't work on Ubuntu (maybe Debian too) when PHP 7 is installed instead of PHP 5.
The paths changed from _/etc/php5/_ to something like _/etc/php/7.0/_.

Could you please provide a way to override the paths manually, so one can easily switch between those versions?

**Comment by tucksaun** [comment]
For your info, you need to put the `blackfire.ini` in `/etc/php/mods-available/` to make it work with `phpenmod`.

**Comment by mvhirsch** [comment]
@tucksaun That's correct. But I can't. 
Currently the `config.pp` will write the `blackfire.ini` into _/etc/php5/mods-available/_ which does not exist on my system. So exists with an error and without writing a file.

My only option would be providing the directory and than copy/link that file in the correct directory. But this seems to be hacky to me.
Anyway, I would really prefer a setting to provide a path manually.

**Comment by Schnitzel** [comment]
@mvhirsch 
implemented the manual settings of the file here: https://github.com/s12v/puppet-blackfire/pull/11

**Comment by mvhirsch** [comment]
Cool, thank you!

So this issue can be closed :-)
