### ISSUE TITLE
Problem with merge() in blackfire.php

### ISSUE THREAD

**Issue by christiansipola** [s12v/puppet-blackfire#7]
I get a error when running the module: 
"Error: merge: unexpected argument type String, only expects hash arguments at /tmp/vagrant-puppet/modules-27c07ec6f70536deab5b55f59f574ecc/blackfire/manifests/php.pp:14 on node dev"

I hade to maketge following patch to make it work:

```
Index: modules/blackfire/manifests/php.pp
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- modules/blackfire/manifests/php.pp  (revision )
+++ modules/blackfire/manifests/php.pp  (revision )
@@ -11,7 +11,14 @@
     log_level => 1,
     agent_timeout => 0.25,
   }
-  $params = merge($default_params, $::blackfire::params)
+  $blackfire_params = {
+    server_id => $::blackfire::server_id,
+    server_token => $::blackfire::server_token,
+    agent => $::blackfire::agent,
+    php => $::blackfire::php,
+    manage_repo => $::blackfire::manage_repo
+  }
+  $params = merge($default_params, $blackfire_params)
   $log_level = 0 + $params['log_level']

   validate_bool($params['manage'])
```

i run puppet 3.8.1, puppetlabs-stdlib 4.1.0.
Is it just me?

**Comment by s12v** [comment]
@christiansipola, could you please show your manifest?

**Comment by christiansipola** [comment]
there som roles and profiles and hiera yaml involved before we in a class we called devtools.pp just have:
class { 'blackfire':
        server_id    => '(removed)',
        server_token => '(removed)',
        notify  => Service['httpd'],
    }

**Comment by christiansipola** [comment]
does not seem to be an issue anymore
